### ISSUE TITLE
Main 87 keyboard layout file missing traces

### ISSUE THREAD

**Issue by Doom4535** [mountainmannm/Bolt-Industries#5]
I was just looking to see if I could edit the main layout to add in some pads for the moved Pico debug header on the Pico W, but it seems that [PCB_Pico 87 layout_2022-02-22.json](https://github.com/mountainmannm/Bolt-Industries/blob/bd00de4329f25a16ad16851f3e5bd4c57badd76e/Hardware/Pico87%20keyboard/PCB_Pico%2087%20layout_2022-02-22.json) is missing all the traces and IC components, it only has the switch footprints and board outline.  Are you able to update the full PCB layout?

**Comment by mountainmannm** [comment]
Hi Doom,
Sorry about that. I Just added a n updated .JSON for that PCB.
